# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('blog', '0003_auto_20170821_1815'), ('blog', '0004_auto_20170821_1824')]

    dependencies = [
        ('blog', '0002_auto_20170821_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
